services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\EmailNotification\:
        resource: '../../src/EmailNotification/*'

    App\EmailNotification\Features\Create\CreateEmailNotificationHandler:
        tags:
            - { name: messenger.message_handler, handles: App\EmailNotification\Features\Create\CreateEmailNotificationCommand }

    App\EmailNotification\Features\Send\SendNotificationHandler:
        tags:
            - { name: messenger.message_handler, handles: App\EmailNotification\Features\Send\SendNotificationCommand }

    App\EmailNotification\Features\Send\Event\EmailNotificationSendingFailedHandler:
        tags:
            - { name: messenger.message_handler, handles: App\Shared\Event\EmailNotification\EmailNotificationSendingFailed }
